-- Timetable System Enhancements for AI-Powered "Plug and Play" Architecture
-- Adds status, season, timing fields, and approval workflow

-- 1. Add new columns to timetable_configs
ALTER TABLE timetable_configs
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PROPOSAL', 'APPROVED')),
ADD COLUMN IF NOT EXISTS season VARCHAR(10) CHECK (season IN ('SUMMER', 'WINTER')),
ADD COLUMN IF NOT EXISTS start_time TIME,
ADD COLUMN IF NOT EXISTS end_time TIME,
ADD COLUMN IF NOT EXISTS period_duration_minutes INTEGER DEFAULT 40,
ADD COLUMN IF NOT EXISTS break_duration_minutes INTEGER DEFAULT 10,
ADD COLUMN IF NOT EXISTS approved_by VARCHAR(255),
ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS notes TEXT;

-- 2. Add index for faster status-based queries
CREATE INDEX IF NOT EXISTS idx_timetable_configs_status ON timetable_configs(school_id, status);

-- 3. Add timetable_slots.time_slot column for actual time (optional, can be computed)
ALTER TABLE timetable_slots
ADD COLUMN IF NOT EXISTS time_slot TIME;

-- 4. Create timetable_notifications table for tracking approval notifications
CREATE TABLE IF NOT EXISTS timetable_notifications (
    id SERIAL PRIMARY KEY,
    school_id VARCHAR(50) NOT NULL,
    config_id VARCHAR(100) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    user_type VARCHAR(20) NOT NULL, -- 'student', 'teacher', 'employee'
    notification_type VARCHAR(50) NOT NULL, -- 'timetable_approved', 'schedule_change'
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    read BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (school_id, config_id) REFERENCES timetable_configs(school_id, config_id) ON DELETE CASCADE
);

-- 5. Add index for notification queries
CREATE INDEX IF NOT EXISTS idx_timetable_notifications_config ON timetable_notifications(school_id, config_id);
CREATE INDEX IF NOT EXISTS idx_timetable_notifications_user ON timetable_notifications(school_id, user_id, user_type);

-- 6. Update existing configs to have PROPOSAL status (since they were generated by AI)
UPDATE timetable_configs SET status = 'PROPOSAL' WHERE status = 'DRAFT';

-- 7. Add comment explaining the new workflow
COMMENT ON TABLE timetable_configs IS 'Timetable configurations with AI proposal workflow. Status: DRAFT (manual scratch), PROPOSAL (AI-generated, awaiting approval), APPROVED (active, triggers notifications).';