import React, { useState } from "react";
import { motion } from "framer-motion";
import { MessageSquare, Sparkles, Mic, Send, X, Download, FileText, Table, Presentation } from "lucide-react";
import StandardButton from "../../../components/ui/StandardButton";
import ChartRenderer from "./ChartRenderer";
import ChartErrorBoundary from "./ChartErrorBoundary";

// ─── Parse markdown table into headers + rows ─────────────────────────────────
function parseMarkdownTable(text) {
  const lines = text.split("\n").filter(l => l.trim().startsWith("|") && l.trim().endsWith("|"));
  if (lines.length < 2) return null;

  const extractCells = (line) => {
    let content = line.trim();
    if (content.startsWith("|")) content = content.slice(1);
    if (content.endsWith("|")) content = content.slice(0, -1);
    return content.split("|").map(c => {
      let val = c.trim();
      return val === "" ? "-" : val;
    });
  };

  const headers = extractCells(lines[0]);
  const isSep = lines[1].replace(/[\|\-\:\s]/g, "").length === 0;
  if (!isSep || headers.length === 0) return null;

  const rows = lines.slice(2).map(extractCells);
  return { headers, rows };
}

// ─── PDF Export via print window ─────────────────────────────────────────────
function exportTableAsPDF(headers, rows, title = "Vidhyam AI Export") {
  if (rows.length > 500) {
    alert("⚠️ Dataset is too large for browser export. Please ask the AI to summarize or limit the results to under 500 rows.");
    return;
  }
  const tableHtml = `
    <html>
      <head>
        <title>${title}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 32px; color: #1a1a2e; }
          h2 { font-size: 20px; color: #6366f1; margin-bottom: 4px; }
          p.subtitle { font-size: 12px; color: #888; margin-bottom: 20px; }
          table { border-collapse: collapse; width: 100%; font-size: 13px; }
          thead tr { background: #6366f1; color: white; }
          th { padding: 10px 14px; text-align: left; font-weight: 600; }
          tbody tr:nth-child(even) { background: #f5f5ff; }
          td { padding: 8px 14px; border-bottom: 1px solid #e8e8f5; }
          .footer { margin-top: 24px; font-size: 11px; color: #aaa; }
        </style>
      </head>
      <body>
        <h2>${title}</h2>
        <p class="subtitle">Generated by Vidhyam AI &bull; ${new Date().toLocaleString()}</p>
        <table>
          <thead><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr></thead>
          <tbody>${rows.map(r => `<tr>${r.map(c => `<td>${c}</td>`).join("")}</tr>`).join("")}</tbody>
        </table>
        <p class="footer">${rows.length} record(s) &bull; Vidhyam School Management System</p>
      </body>
    </html>
  `;
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(tableHtml);
  win.document.close();
  setTimeout(() => { win.print(); }, 300);
}

// ─── CSV Export ───────────────────────────────────────────────────────────────
function exportTableAsCSV(headers, rows, filename = "Vidhyam_AI_Export.csv") {
  if (rows.length > 500) {
    alert("⚠️ Dataset is too large for browser export. Please ask the AI to summarize or limit the results to under 500 rows.");
    return;
  }
  const escapeCell = (cell) => {
    const stringCell = String(cell);
    if (stringCell.includes(",") || stringCell.includes("\"") || stringCell.includes("\n")) {
      return `"${stringCell.replace(/"/g, '""')}"`;
    }
    return stringCell;
  };
  const csvContent = [
    headers.map(escapeCell).join(","),
    ...rows.map(row => row.map(escapeCell).join(","))
  ].join("\n");
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// ─── PPT Export ───────────────────────────────────────────────────────────────
function exportTableAsPPT(headers, rows, filename = "Vidhyam_AI_Presentation.pptx") {
  if (rows.length > 500) {
    alert("⚠️ Dataset is too large for presentation export. Please ask the AI to summarize or limit the results to under 500 rows.");
    return;
  }
  const pptx = new PptxGenJS();
  const slide = pptx.addSlide();
  
  // Title
  slide.addText("Vidhyam AI Data Export", {
    x: 0.5, y: 0.5, w: "90%", h: 0.5,
    fontSize: 24, bold: true, color: "363636"
  });

  // Table Data
  const tableData = [
    headers.map(h => ({ text: String(h), options: { bold: true, fill: "6366f1", color: "ffffff" } })),
    ...rows.map(row => row.map(cell => String(cell)))
  ];

  slide.addTable(tableData, {
    x: 0.5, y: 1.5, w: "90%",
    border: { pt: 1, color: "cccccc" },
    fill: "f8f9fa",
    fontSize: 12,
    autoPage: true // Automatically create new slides if table is too long!
  });

  pptx.writeFile({ fileName: filename });
}

// ─── Data Table Component ─────────────────────────────────────────────────────

const renderUserMessage = (text) => {
  if (!text) return null;
  const parts = text.split(/(@[a-zA-Z0-9_]+)/g);
  return (
    <span>
      {parts.map((part, i) => {
        if (part.startsWith('@')) {
          return (
            <span key={i} className="inline-flex items-center px-2 py-0.5 rounded-md bg-white/20 border border-white/40 text-[10px] font-bold uppercase tracking-wider mr-1 shadow-sm backdrop-blur-sm">
              {part.substring(1)}
            </span>
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </span>
  );
};
function DataTable({ headers, rows }) {
  return (
    <div className="my-3 rounded-xl overflow-hidden border border-white/10">
      <div className="overflow-x-auto">
        <table className="w-full text-xs border-collapse min-w-[400px]">
          <thead>
            <tr style={{ background: "rgba(99, 102, 241, 0.25)" }}>
              {headers.map((h, i) => (
                <th key={i} className="px-3 py-2.5 text-left font-semibold text-indigo-200 whitespace-nowrap border-b border-white/10">
                  {h}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, ri) => (
              <tr
                key={ri}
                style={{ background: ri % 2 === 0 ? "rgba(255,255,255,0.03)" : "rgba(255,255,255,0.06)" }}
                className="hover:bg-indigo-500/10 transition-colors border-b border-white/5"
              >
                {row.map((cell, ci) => (
                  <td key={ci} className="px-3 py-2 text-slate-200 whitespace-nowrap">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div
        className="flex items-center justify-between px-3 py-2 border-t border-white/10"
        style={{ background: "rgba(0,0,0,0.2)" }}
      >
        <span className="text-[10px] text-slate-500">{rows.length} record{rows.length !== 1 ? "s" : ""}</span>
        <div className="flex gap-2">
          <button
            onClick={() => exportTableAsCSV(headers, rows)}
            className="flex items-center gap-1.5 text-[11px] text-emerald-400 hover:text-emerald-300 transition-colors px-2.5 py-1 rounded-lg border border-emerald-500/30 hover:border-emerald-400/50 hover:bg-emerald-500/10"
          >
            <Table size={11} />
            Export CSV
          </button>
          <button
            onClick={() => exportTableAsPDF(headers, rows)}
            className="flex items-center gap-1.5 text-[11px] text-indigo-400 hover:text-indigo-300 transition-colors px-2.5 py-1 rounded-lg border border-indigo-500/30 hover:border-indigo-400/50 hover:bg-indigo-500/10"
          >
            <FileText size={11} />
            Export PDF
          </button>
          <button
            onClick={() => exportTableAsPPT(headers, rows)}
            className="flex items-center gap-1.5 text-[11px] text-orange-400 hover:text-orange-300 transition-colors px-2.5 py-1 rounded-lg border border-orange-500/30 hover:border-orange-400/50 hover:bg-orange-500/10"
          >
            <Presentation size={11} />
            Export PPT
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Parse [SUGGESTIONS:{...}] block from message text ───────────────────────
function parseSuggestions(text) {
  if (!text) return { cleanText: text || "", suggestions: [] };
  const match = text.match(/\[SUGGESTIONS:(\{.*?\})\]$/s);
  if (!match) return { cleanText: text, suggestions: [] };
  try {
    const data = JSON.parse(match[1]);
    return {
      cleanText: text.slice(0, text.length - match[0].length).trim(),
      suggestions: Array.isArray(data.questions) ? data.questions : [],
    };
  } catch {
    return { cleanText: text, suggestions: [] };
  }
}

// ─── Inline bold parser ───────────────────────────────────────────────────────
function parseInlineBold(text) {
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((p, i) => {
    if (p.startsWith("**") && p.endsWith("**")) {
      return <strong key={i} className="font-semibold text-white">{p.slice(2, -2)}</strong>;
    }
    return p;
  });
}

// ─── Main markdown renderer ───────────────────────────────────────────────────
function renderMarkdown(text) {
  if (!text) return null;

  // Split by code blocks first
  const codeBlockParts = text.split(/(```[\s\S]*?```)/g);

  return codeBlockParts.map((part, partIdx) => {
    // Handle fenced code blocks
    if (part.startsWith("```") && part.endsWith("```")) {
      const inner = part.slice(3, -3).trim();
      const firstNewline = inner.indexOf("\n");
      const lang = firstNewline > -1 ? inner.slice(0, firstNewline).trim().toLowerCase() : "";
      const code = firstNewline > -1 ? inner.slice(firstNewline + 1) : inner;

      if (lang === "chart") {
        return (
          <ChartErrorBoundary key={partIdx}>
            <ChartRenderer jsonString={code} />
          </ChartErrorBoundary>
        );
      }

      return (
        <div key={partIdx} className="my-2 bg-black/60 rounded-lg overflow-hidden border border-white/5 font-mono">
          {lang && (
            <div className="bg-white/5 px-3 py-1 text-[10px] text-slate-400 uppercase tracking-wider border-b border-white/5">
              {lang}
            </div>
          )}
          <pre className="p-3 overflow-x-auto text-[11px] text-slate-100 leading-relaxed">
            <code>{code}</code>
          </pre>
        </div>
      );
    }

    // For normal text: scan line by line, detect table blocks
    const lines = part.split("\n");
    const elements = [];
    let i = 0;

    while (i < lines.length) {
      const line = lines[i];

      // Detect start of markdown table
      if (line.trim().startsWith("|") && line.trim().endsWith("|")) {
        // Gather all consecutive pipe lines
        const tableLines = [];
        while (i < lines.length && lines[i].trim().startsWith("|") && lines[i].trim().endsWith("|")) {
          tableLines.push(lines[i]);
          i++;
        }
        const parsed = parseMarkdownTable(tableLines.join("\n"));
        if (parsed && parsed.rows.length > 0) {
          elements.push(
            <DataTable key={`tbl-${partIdx}-${elements.length}`} headers={parsed.headers} rows={parsed.rows} />
          );
        }
        continue;
      }

      // Bullet list
      if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
        elements.push(
          <ul key={`ul-${partIdx}-${i}`} className="list-disc pl-5 my-1 text-xs text-slate-200">
            <li>{parseInlineBold(line.trim().slice(2))}</li>
          </ul>
        );
        i++;
        continue;
      }

      // Heading
      if (line.trim().startsWith("# ")) {
        elements.push(
          <h3 key={`h-${partIdx}-${i}`} className="text-sm font-bold text-white mt-3 mb-1">
            {line.trim().slice(2)}
          </h3>
        );
        i++;
        continue;
      }

      // Empty line → spacer
      if (line.trim() === "") {
        if (elements.length > 0) {
          elements.push(<div key={`sp-${partIdx}-${i}`} className="h-1" />);
        }
        i++;
        continue;
      }

      // Normal paragraph
      elements.push(
        <p key={`p-${partIdx}-${i}`} className="my-1 text-xs text-slate-200 leading-relaxed">
          {parseInlineBold(line)}
        </p>
      );
      i++;
    }

    return <React.Fragment key={partIdx}>{elements}</React.Fragment>;
  });
}

// ─── Main Component ───────────────────────────────────────────────────────────
export default function AiChatWindow({
  chatHistory,
  loading,
  query,
  setQuery,
  handleSend,
  handleStopGeneration,
  handleInvalidateCache,
  scrollRef,
  autocompleteSuggestions = [],
  showAutocomplete = false,
  setShowAutocomplete,
}) {
  const handleSuggestionClick = (suggestion) => {
    setQuery(suggestion);
    // Auto submit after a tick so the input value is set
    setTimeout(() => {
      const fakeEvent = { preventDefault: () => {} };
      handleSend(fakeEvent, suggestion);
    }, 50);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.1 }}
      className="flex-1 border border-[var(--glass-border)] rounded-2xl flex flex-col overflow-hidden relative min-w-0"
      style={{ background: "var(--bg-secondary)" }}
    >
      {/* Header */}
      <div className="p-3 border-b border-[var(--glass-border)] flex items-center justify-between"
        style={{ background: "rgba(0,0,0,0.15)" }}>
        <div className="flex items-center gap-2 min-w-0">
          <MessageSquare size={14} className="text-primary animate-pulse" />
          <span className="text-xs font-semibold text-[var(--text-main)] truncate max-w-[200px] lg:max-w-xs">
            Vidhyam AI Assistant
          </span>
        </div>
      </div>

      {/* Chat Messages */}
      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar scroll-smooth"
        style={{ background: "rgba(0,0,0,0.1)" }}
      >
        {chatHistory.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center max-w-sm mx-auto opacity-75">
            <div className="w-12 h-12 rounded-2xl bg-primary/10 border border-primary/20 flex items-center justify-center mb-4">
              <Sparkles size={24} className="text-primary animate-pulse" />
            </div>
            <h2 className="text-sm font-semibold text-[var(--text-main)] mb-1">Vidhyam AI Assistant</h2>
            <p className="text-xs text-[var(--text-muted)] leading-relaxed">
              School data ke baare mein kuch bhi poochho — students, fees, attendance, ya koi bhi analytics.
            </p>
          </div>
        ) : (
          chatHistory.map((msg, i) => {
            if (msg.role === "system") {
              return (
                <motion.div
                  key={msg.id || i}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex justify-center"
                >
                  <span className="text-[10px] text-[var(--text-muted)] bg-black/20 px-2.5 py-1 rounded-full border border-white/5 font-medium">
                    {msg.content}
                  </span>
                </motion.div>
              );
            }
            const isUser = msg.role === "user";
            let prevUserMsg = "";
            if (!isUser && i > 0 && chatHistory[i-1].role === "user") {
              prevUserMsg = chatHistory[i-1].content;
            }

            let { cleanText, suggestions } = isUser
              ? { cleanText: msg.content, suggestions: [] }
              : parseSuggestions(msg.content);

            if (msg.relatedPrompts && msg.relatedPrompts.length > 0) {
              suggestions = msg.relatedPrompts.map(p => p.text || p);
            }

            return (
              <motion.div
                key={msg.id || i}
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                className={`flex ${isUser ? "justify-end" : "justify-start"}`}
              >
                <div
                  className={`max-w-[88%] px-3.5 py-2.5 rounded-2xl text-xs leading-relaxed shadow-sm ${
                    isUser
                      ? "bg-primary text-white rounded-tr-none"
                      : "rounded-tl-none border border-white/10"
                  }`}
                  style={
                    isUser
                      ? {}
                      : { background: "rgba(15, 15, 30, 0.75)", color: "#e2e8f0" }
                  }
                >
                  {isUser ? (
                    <p className="whitespace-pre-wrap">{cleanText}</p>
                  ) : (
                    <>
                      {/* Show animated thinking chip while streaming with no data yet */}
                      {msg.isStreaming && cleanText.trim() === "" && (
                        <div className="flex items-center gap-2 py-1">
                          <div className="flex gap-1">
                            <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.3s]" />
                            <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.15s]" />
                            <div className="w-1.5 h-1.5 bg-indigo-400 rounded-full animate-bounce" />
                          </div>
                          <span className="text-[11px] text-indigo-300 italic">Thinking...</span>
                        </div>
                      )}

                      {/* Show thinking chip as a badge above the content while data is still streaming in */}
                      {msg.isStreaming && cleanText.trim() !== "" && (
                        <div className="flex items-center gap-1.5 mb-2 pb-2 border-b border-white/10">
                          <div className="flex gap-0.5">
                            <div className="w-1 h-1 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.3s]" />
                            <div className="w-1 h-1 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.15s]" />
                            <div className="w-1 h-1 bg-indigo-400 rounded-full animate-bounce" />
                          </div>
                          <span className="text-[10px] text-indigo-400 italic">Generating...</span>
                        </div>
                      )}

                      {/* Render actual content */}
                      {cleanText.trim() && renderMarkdown(cleanText)}

                      {/* User Feedback for Incorrect Cache */}
                      {cleanText.trim() && !msg.isStreaming && prevUserMsg && handleInvalidateCache && (
                        <div className="mt-2 flex justify-end">
                          <button
                            onClick={() => handleInvalidateCache(prevUserMsg)}
                            title="Result is wrong? Click to remove from cache and regenerate."
                            className="text-[10px] text-slate-500 hover:text-red-400 flex items-center gap-1 px-1.5 py-0.5 rounded hover:bg-red-500/10 transition-colors"
                          >
                            <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 14H5.236a2 2 0 01-1.789-2.894l3.5-7A2 2 0 018.736 3h4.018a2 2 0 01.485.06l3.76.94m-7 10v5a2 2 0 002 2h.096c.5 0 .905-.405.905-.904 0-.715.211-1.413.608-2.008L17 13V4m-7 10h2m5-10h2a2 2 0 012 2v6a2 2 0 01-2 2h-2.5" />
                            </svg>
                            Flag as Incorrect
                          </button>
                        </div>
                      )}

                      {/* Suggestion chips */}
                      {suggestions.length > 0 && (
                        <div className="mt-3 pt-2.5 border-t border-white/10 flex flex-wrap gap-1.5">
                          <p className="w-full text-[10px] text-slate-500 mb-0.5">Aage pooch sakte ho:</p>
                          {suggestions.map((q, si) => (
                            <button
                              key={si}
                              onClick={() => handleSuggestionClick(q)}
                              className="text-[11px] px-2.5 py-1 rounded-full border border-indigo-500/40 text-indigo-300 hover:bg-indigo-500/15 hover:border-indigo-400/60 hover:text-indigo-200 transition-all"
                            >
                              {q}
                            </button>
                          ))}
                        </div>
                      )}
                    </>
                  )}

                  <span className="text-[9px] text-slate-500 block text-right mt-1.5 opacity-60">
                    {new Date(msg.created_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                  </span>
                </div>
              </motion.div>
            );
          })
        )}

        {/* Typing indicator */}
        {loading && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex justify-start"
          >
            <div
              className="px-4 py-3 rounded-2xl rounded-tl-none border border-white/10"
              style={{ background: "rgba(15, 15, 30, 0.75)" }}
            >
              <div className="flex gap-1.5 items-center">
                <div className="w-1.5 h-1.5 bg-primary rounded-full animate-bounce [animation-delay:-0.3s]" />
                <div className="w-1.5 h-1.5 bg-primary rounded-full animate-bounce [animation-delay:-0.15s]" />
                <div className="w-1.5 h-1.5 bg-primary rounded-full animate-bounce" />
              </div>
            </div>
          </motion.div>
        )}
      </div>

      {/* Input */}
      <div className="p-3 border-t border-[var(--glass-border)] relative" style={{ background: "var(--bg-secondary)" }}>
        {/* Autocomplete Overlay */}
        {showAutocomplete && autocompleteSuggestions.length > 0 && (
          <div className="absolute bottom-[60px] left-3 right-3 bg-[#11111a] border border-indigo-500/30 rounded-xl overflow-hidden shadow-xl shadow-indigo-500/10 z-10 backdrop-blur-md">
            <div className="px-3 py-2 text-[10px] text-indigo-300/70 border-b border-indigo-500/20 uppercase tracking-wider font-semibold">
              Suggested Queries
            </div>
            <div className="max-h-48 overflow-y-auto custom-scrollbar">
              {autocompleteSuggestions.map((sug, i) => (
                <button
                  key={i}
                  type="button"
                  onClick={() => {
                    handleSuggestionClick(sug.text);
                    if (setShowAutocomplete) setShowAutocomplete(false);
                  }}
                  className="w-full text-left px-3 py-2.5 text-xs text-slate-200 hover:bg-indigo-500/20 hover:text-indigo-200 transition-colors flex justify-between items-center group border-b border-white/5 last:border-0"
                >
                  <span className="truncate pr-2">{sug.text}</span>
                  <span className="text-[10px] text-slate-500 group-hover:text-indigo-400 transition-colors whitespace-nowrap">
                    {sug.count > 0 ? `${sug.count} searches` : ''}
                  </span>
                </button>
              ))}
            </div>
          </div>
        )}

        <form
          onSubmit={(e) => {
            if (setShowAutocomplete) setShowAutocomplete(false);
            handleSend(e);
          }}
          className="relative group"
        >
          <input
            type="text"
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              if (setShowAutocomplete) setShowAutocomplete(true);
            }}
            placeholder="School data ke baare mein kuch bhi poochho..."
            disabled={loading}
            className="w-full border border-[var(--glass-border)] rounded-xl h-11 pl-4 pr-24 text-xs text-[var(--text-main)] placeholder-[var(--text-muted)] focus:outline-none focus:border-primary/50 transition-all font-medium"
            style={{ background: "var(--bg-main)" }}
          />
          <div className="absolute right-1.5 top-1.5 bottom-1.5 flex gap-1 items-center">
            <button type="button" className="p-1 px-2 text-[var(--text-muted)] hover:text-primary transition-colors">
              <Mic size={14} />
            </button>
            {loading ? (
              <button
                type="button"
                onClick={handleStopGeneration}
                className="w-8 h-8 rounded-xl flex items-center justify-center bg-rose-500 hover:bg-rose-600 text-white active:scale-95 transition-all cursor-pointer shadow-md shadow-rose-500/25 animate-pulse"
                title="Stop generation"
              >
                <X className="w-4 h-4" />
              </button>
            ) : (
              <StandardButton
                type="submit"
                disabled={!query.trim() || loading}
                icon={Send}
                size="xs"
              />
            )}
          </div>
        </form>
      </div>
    </motion.div>
  );
}
