# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiServiceStub:
    """Optional: for compiling in Rust
    We don't need any complex imports if we use strings for JSON payloads

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOcr = channel.unary_unary(
                '/ai_service.AiService/ProcessOcr',
                request_serializer=ai__service__pb2.OcrRequest.SerializeToString,
                response_deserializer=ai__service__pb2.OcrResponse.FromString,
                _registered_method=True)
        self.GenerateTasks = channel.unary_unary(
                '/ai_service.AiService/GenerateTasks',
                request_serializer=ai__service__pb2.TasksRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TasksResponse.FromString,
                _registered_method=True)
        self.ReorganizeTasks = channel.unary_unary(
                '/ai_service.AiService/ReorganizeTasks',
                request_serializer=ai__service__pb2.TasksRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TasksResponse.FromString,
                _registered_method=True)


class AiServiceServicer:
    """Optional: for compiling in Rust
    We don't need any complex imports if we use strings for JSON payloads

    """

    def ProcessOcr(self, request, context):
        """OCR processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateTasks(self, request, context):
        """Generate weekly tasks for an employee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReorganizeTasks(self, request, context):
        """Reorganize weekly tasks for an employee
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOcr': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOcr,
                    request_deserializer=ai__service__pb2.OcrRequest.FromString,
                    response_serializer=ai__service__pb2.OcrResponse.SerializeToString,
            ),
            'GenerateTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateTasks,
                    request_deserializer=ai__service__pb2.TasksRequest.FromString,
                    response_serializer=ai__service__pb2.TasksResponse.SerializeToString,
            ),
            'ReorganizeTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ReorganizeTasks,
                    request_deserializer=ai__service__pb2.TasksRequest.FromString,
                    response_serializer=ai__service__pb2.TasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiService:
    """Optional: for compiling in Rust
    We don't need any complex imports if we use strings for JSON payloads

    """

    @staticmethod
    def ProcessOcr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/ProcessOcr',
            ai__service__pb2.OcrRequest.SerializeToString,
            ai__service__pb2.OcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/GenerateTasks',
            ai__service__pb2.TasksRequest.SerializeToString,
            ai__service__pb2.TasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReorganizeTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AiService/ReorganizeTasks',
            ai__service__pb2.TasksRequest.SerializeToString,
            ai__service__pb2.TasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
