# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_service.proto\x12\nai_service\"C\n\nOcrRequest\x12\x11\n\tschool_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ile_url\x18\x02 \x01(\t\x12\x10\n\x08\x64oc_type\x18\x03 \x01(\t\"T\n\x0bOcrResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x1d\n\x15\x65xtracted_fields_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"7\n\x0cTasksRequest\x12\x11\n\tschool_id\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"J\n\rTasksResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tdata_json\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2\xd8\x01\n\tAiService\x12=\n\nProcessOcr\x12\x16.ai_service.OcrRequest\x1a\x17.ai_service.OcrResponse\x12\x44\n\rGenerateTasks\x12\x18.ai_service.TasksRequest\x1a\x19.ai_service.TasksResponse\x12\x46\n\x0fReorganizeTasks\x12\x18.ai_service.TasksRequest\x1a\x19.ai_service.TasksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST']._serialized_start=32
  _globals['_OCRREQUEST']._serialized_end=99
  _globals['_OCRRESPONSE']._serialized_start=101
  _globals['_OCRRESPONSE']._serialized_end=185
  _globals['_TASKSREQUEST']._serialized_start=187
  _globals['_TASKSREQUEST']._serialized_end=242
  _globals['_TASKSRESPONSE']._serialized_start=244
  _globals['_TASKSRESPONSE']._serialized_end=318
  _globals['_AISERVICE']._serialized_start=321
  _globals['_AISERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
