// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlq4XZV799VinDqnkGpv_kq62sz3jllw',
    appId: '1:671964901221:web:ef0db9be72eff6398abb8c',
    messagingSenderId: '671964901221',
    projectId: 'modernschool-d2054',
    authDomain: 'modernschool-d2054.firebaseapp.com',
    storageBucket: 'modernschool-d2054.firebasestorage.app',
    measurementId: 'G-134J8YZGJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLikXQ-iRdVbmHbaq2-j_fPfLujWfraKQ',
    appId: '1:671964901221:android:12cc176b38633a008abb8c',
    messagingSenderId: '671964901221',
    projectId: 'modernschool-d2054',
    storageBucket: 'modernschool-d2054.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAl4HDbzf1pcZqqU96x3R9JOF09t9QmzE',
    appId: '1:671964901221:ios:0ee79314b48e25dc8abb8c',
    messagingSenderId: '671964901221',
    projectId: 'modernschool-d2054',
    storageBucket: 'modernschool-d2054.firebasestorage.app',
    iosBundleId: 'com.example.adhyapk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAl4HDbzf1pcZqqU96x3R9JOF09t9QmzE',
    appId: '1:671964901221:ios:0ee79314b48e25dc8abb8c',
    messagingSenderId: '671964901221',
    projectId: 'modernschool-d2054',
    storageBucket: 'modernschool-d2054.firebasestorage.app',
    iosBundleId: 'com.example.adhyapk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlq4XZV799VinDqnkGpv_kq62sz3jllw',
    appId: '1:671964901221:web:14ceeeff5a87dad48abb8c',
    messagingSenderId: '671964901221',
    projectId: 'modernschool-d2054',
    authDomain: 'modernschool-d2054.firebaseapp.com',
    storageBucket: 'modernschool-d2054.firebasestorage.app',
    measurementId: 'G-7WHVGWKSSJ',
  );
}
