import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_animate/flutter_animate.dart';
import 'package:chatra/core/network/api_service.dart';
import 'package:chatra/features/attendance/services/offline_sync_service.dart';
import 'package:chatra/widgets/glass_card.dart';
import 'package:chatra/widgets/animated_gradient_bg.dart';

/// QR Scanner screen for mobile attendance marking.
/// Scans the QR code generated by /attendance/:schoolId/qr-attendance,
/// captures GPS location, and submits to /attendance/:schoolId/mobile-attendance.
class QrAttendanceScreen extends StatefulWidget {
  const QrAttendanceScreen({super.key});

  @override
  State<QrAttendanceScreen> createState() => _QrAttendanceScreenState();
}

class _QrAttendanceScreenState extends State<QrAttendanceScreen>
    with SingleTickerProviderStateMixin {
  final MobileScannerController _scanner = MobileScannerController(
    facing: CameraFacing.back,
    detectionSpeed: DetectionSpeed.noDuplicates,
  );
  final FlutterSecureStorage _storage = const FlutterSecureStorage();
  late AnimationController _pulseController;

  bool _isProcessing = false;
  bool _isDone = false;
  String? _statusMessage;
  bool _isSuccess = false;

  @override
  void initState() {
    super.initState();
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 2),
    )..repeat(reverse: true);
  }

  @override
  void dispose() {
    _scanner.dispose();
    _pulseController.dispose();
    super.dispose();
  }

  // ── GPS Permission & Location ──────────────────────────────────────────────

  Future<Position?> _getLocation() async {
    bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      _showMessage('Location services are disabled.', isError: true);
      return null;
    }

    LocationPermission permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        _showMessage('Location permission denied.', isError: true);
        return null;
      }
    }
    if (permission == LocationPermission.deniedForever) {
      _showMessage('Location permissions permanently denied.', isError: true);
      return null;
    }

    return await Geolocator.getCurrentPosition(
      desiredAccuracy: LocationAccuracy.high,
      timeLimit: const Duration(seconds: 10),
    );
  }

  // ── QR Detected ────────────────────────────────────────────────────────────

  Future<void> _onQrDetected(BarcodeCapture capture) async {
    if (_isProcessing || _isDone) return;

    final barcode = capture.barcodes.firstOrNull;
    if (barcode?.rawValue == null) return;

    final qrData = barcode!.rawValue!;

    // Expected format: attendance://<schoolId>/<classId>?token=<uuid>&expires=<timestamp>
    if (!qrData.startsWith('attendance://')) {
      _showMessage('Invalid QR code. Please scan the attendance QR.', isError: true);
      return;
    }

    setState(() => _isProcessing = true);
    HapticFeedback.mediumImpact();
    _scanner.stop();

    try {
      // Parse QR data
      final uri = Uri.parse(qrData.replaceFirst('attendance://', 'https://'));
      final token = uri.queryParameters['token'];
      final expiresStr = uri.queryParameters['expires'];

      if (token == null || token.isEmpty) {
        _showMessage('Invalid QR: missing token.', isError: true);
        setState(() => _isProcessing = false);
        return;
      }

      // Check expiry
      if (expiresStr != null) {
        final expiry = int.tryParse(expiresStr) ?? 0;
        final now = DateTime.now().millisecondsSinceEpoch ~/ 1000;
        if (now > expiry) {
          _showMessage('QR code has expired. Ask teacher to regenerate.', isError: true);
          setState(() => _isProcessing = false);
          return;
        }
      }

      // Get location
      _showMessage('Getting your location…');
      final position = await _getLocation();
      if (position == null) {
        setState(() => _isProcessing = false);
        return;
      }

      // Get stored credentials
      final schoolId = await _storage.read(key: 'school_id') ?? '';
      final userId = await _storage.read(key: 'student_id') ?? '';
      final jwtToken = await _storage.read(key: 'jwt_token') ?? '';

      if (schoolId.isEmpty || userId.isEmpty) {
        _showMessage('Not logged in. Please restart the app.', isError: true);
        setState(() => _isProcessing = false);
        return;
      }

      // Submit attendance
      _showMessage('Marking attendance…');
      try {
        final response = await http.post(
          Uri.parse('${ApiService.apiBase}/operations/attendance/$schoolId/mobile-attendance'),
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer $jwtToken',
          },
          body: jsonEncode({
            'token': token,
            'user_id': userId,
            'role': 'student',
            'latitude': position.latitude,
            'longitude': position.longitude,
            'accuracy': position.accuracy,
            'device_id': 'flutter_app',
          }),
        ).timeout(const Duration(seconds: 10));

        final body = jsonDecode(response.body) as Map<String, dynamic>;

        if (response.statusCode == 200 && body['success'] == true) {
          setState(() {
            _isDone = true;
            _isSuccess = true;
            _statusMessage = 'Attendance marked successfully! ✓';
            _isProcessing = false;
          });
          HapticFeedback.heavyImpact();
          await Future.delayed(const Duration(seconds: 2));
          if (mounted) Navigator.of(context).pop(true);
        } else {
          final errMsg = body['message']?.toString() ?? 'Attendance failed (${response.statusCode})';
          _showMessage(errMsg, isError: true);
          setState(() => _isProcessing = false);
          await Future.delayed(const Duration(seconds: 2));
          _scanner.start();
        }
      } catch (e) {
        // Network error - offer offline save
        debugPrint('[QrScanner] Network error, offering offline save: $e');
        _showOfflineOption(
          userId: userId,
          schoolId: schoolId,
          lat: position.latitude,
          lng: position.longitude,
        );
      }
    } catch (e) {
      _showMessage('Error: $e', isError: true);
      setState(() => _isProcessing = false);
      await Future.delayed(const Duration(seconds: 2));
      if (mounted) _scanner.start();
    }
  }

  void _showOfflineOption({
    required String userId,
    required String schoolId,
    required double lat,
    required double lng,
  }) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        backgroundColor: const Color(0xFF1A1A1C),
        title: const Text('Connection Error', style: TextStyle(color: Colors.white)),
        content: const Text(
          'Unable to connect to the server. Would you like to save this attendance locally and sync it later?',
          style: TextStyle(color: Colors.white70),
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              setState(() => _isProcessing = false);
              _scanner.start();
            },
            child: const Text('Cancel', style: TextStyle(color: Colors.grey)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(backgroundColor: Colors.amber),
            onPressed: () async {
              Navigator.pop(context);
              final now = DateTime.now();
              final record = OfflineAttendanceRecord(
                userId: userId,
                schoolId: schoolId,
                role: 'student',
                date: now.toIso8601String().split('T')[0],
                status: 'present',
                latitude: lat,
                longitude: lng,
                createdAt: now.millisecondsSinceEpoch,
              );
              
              await OfflineSyncService.instance.saveOfflineRecord(record);
              
              setState(() {
                _isDone = true;
                _isSuccess = true;
                _statusMessage = 'Saved offline! Sync later. ✓';
                _isProcessing = false;
              });
              
              await Future.delayed(const Duration(seconds: 2));
              if (mounted) Navigator.of(context).pop(true);
            },
            child: const Text('Save Offline', style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  void _showMessage(String msg, {bool isError = false}) {
    setState(() {
      _statusMessage = msg;
      _isSuccess = !isError;
    });
  }

  // ── UI ─────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: const Text('Scan Attendance QR',
            style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          IconButton(
            icon: const Icon(Icons.flash_on_rounded, color: Colors.white),
            tooltip: 'Toggle Torch',
            onPressed: () => _scanner.toggleTorch(),
          ),
        ],
      ),
      body: AnimatedGradientBg(
        child: Stack(
          children: [
            // Camera preview
            if (!_isDone)
              MobileScanner(
                controller: _scanner,
                onDetect: _onQrDetected,
              ),

            // Overlay
            if (!_isDone) _buildScannerOverlay(),

            // Success state
            if (_isDone) _buildSuccessState(),

            // Status bar
            Positioned(
              bottom: 40,
              left: 20,
              right: 20,
              child: _buildStatusBar(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildScannerOverlay() {
    return AnimatedBuilder(
      animation: _pulseController,
      builder: (context, child) {
        final pulse = 0.8 + 0.2 * _pulseController.value;
        return Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const SizedBox(height: 60),
              Stack(
                alignment: Alignment.center,
                children: [
                  // Pulsing ring
                  Container(
                    width: 260 * pulse,
                    height: 260 * pulse,
                    decoration: BoxDecoration(
                      border: Border.all(
                        color: Colors.white.withOpacity(0.15 * pulse),
                        width: 2,
                      ),
                      borderRadius: BorderRadius.circular(24),
                    ),
                  ),
                  // Scanner box
                  Container(
                    width: 240,
                    height: 240,
                    decoration: BoxDecoration(
                      border: Border.all(
                        color: _isProcessing ? Colors.amber : Colors.white,
                        width: 3,
                      ),
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                  // Corner accents
                  ..._buildCornerAccents(),
                ],
              ),
              const SizedBox(height: 24),
              Text(
                _isProcessing ? 'Processing…' : 'Align QR code within the box',
                style: TextStyle(
                  color: Colors.white.withOpacity(0.85),
                  fontSize: 15,
                  fontWeight: FontWeight.w500,
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  List<Widget> _buildCornerAccents() {
    const size = 24.0;
    const thickness = 4.0;
    const color = Colors.white;
    final radius = BorderRadius.circular(4);

    Widget corner({required Alignment alignment, required BorderRadius borderRadius}) {
      return Positioned.fill(
        child: Align(
          alignment: alignment,
          child: Container(
            width: size,
            height: size,
            margin: const EdgeInsets.all(120 - size * 0.5),
            decoration: BoxDecoration(
              border: Border.all(color: color, width: thickness),
              borderRadius: borderRadius,
            ),
          ),
        ),
      );
    }

    return [
      corner(alignment: Alignment.topLeft, borderRadius: const BorderRadius.only(topLeft: Radius.circular(4))),
      corner(alignment: Alignment.topRight, borderRadius: const BorderRadius.only(topRight: Radius.circular(4))),
      corner(alignment: Alignment.bottomLeft, borderRadius: const BorderRadius.only(bottomLeft: Radius.circular(4))),
      corner(alignment: Alignment.bottomRight, borderRadius: const BorderRadius.only(bottomRight: Radius.circular(4))),
    ];
  }

  Widget _buildSuccessState() {
    return Center(
      child: GlassCard(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.check_circle_outline_rounded, color: Colors.greenAccent, size: 72)
                .animate().scale(duration: 400.ms, curve: Curves.elasticOut),
            const SizedBox(height: 16),
            const Text('Attendance Marked!',
                style: TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.bold)),
            const SizedBox(height: 8),
            Text(_statusMessage ?? '',
                textAlign: TextAlign.center,
                style: TextStyle(color: Colors.white.withOpacity(0.7))),
          ],
        ),
      ),
    ).animate().fadeIn(duration: 300.ms);
  }

  Widget _buildStatusBar() {
    if (_statusMessage == null) return const SizedBox.shrink();
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: _isSuccess
            ? Colors.greenAccent.withOpacity(0.15)
            : Colors.redAccent.withOpacity(0.15),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: (_isSuccess ? Colors.greenAccent : Colors.redAccent).withOpacity(0.4),
        ),
      ),
      child: Row(
        children: [
          Icon(
            _isSuccess ? Icons.check_circle_rounded : Icons.error_rounded,
            color: _isSuccess ? Colors.greenAccent : Colors.redAccent,
            size: 18,
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              _statusMessage!,
              style: TextStyle(
                color: _isSuccess ? Colors.greenAccent : Colors.redAccent,
                fontSize: 13,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
          if (_isProcessing)
            const SizedBox(
              width: 16,
              height: 16,
              child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white60),
            ),
        ],
      ),
    );
  }
}
